### ISSUE TITLE
Autenticação senha única

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/empresta_symfony#24]

**Comment by thiagogomesverissimo** [comment]
Não implementei antes, pois aqui quem faz o empréstimo são pessoas terceirizadas. Na ECA, não?

**Comment by alecostaweb** [comment]
Na biblioteca não, mas na portaria que vai emprestar kits de salas de aula serão os terceirizados. Podemos colocar um chaveamento, pois teremos uma instalação para cada setor.

**Comment by alecostaweb** [comment]
Algo como senhaUnica = true

**Comment by thiagogomesverissimo** [comment]
sim. Vamos fazer isso.
