### ISSUE TITLE
Erro no Deploy

### ISSUE THREAD

**Issue by leandroramos** [uspdev/empresta_symfony#27]
Ao rodar o composer install:
`[ErrorException]                                                                                                                                                                            
  Declaration of Symfony\Flex\ParallelDownloader::getRemoteContents($originUrl, $fileUrl, $context) should be compatible with Composer\Util\RemoteFilesystem::getRemoteContents($originUrl,   
  $fileUrl, $context, ?array &$responseHeaders = NULL)`

**Comment by thiagogomesverissimo** [comment]
qual versão do php está rodando?

**Comment by leandroramos** [comment]
Estou usando a 7.2.10. Funcionou depois de dar update no flex:
`composer update symfony/flex --no-plugins`, mas não mandei PR

**Comment by alecostaweb** [comment]
Tive este mesmo erro com php7.3, apaguei o projeto, clonei novamente e funcionou. Não sei porque. rs

**Comment by alecostaweb** [comment]
Agora outro erro acontece no php bin/console doctrine:migrations:migrate
In Version20180530171402.php line 11:                                                                         
  Attempted to load class "AbstractMigration" from namespace "Doctrine\DBAL\Migrations".  
  Did you forget a "use" statement for "Doctrine\Migrations\AbstractMigration"?

**Comment by alecostaweb** [comment]
Como faz um ano que não tem alteração nas tabelas, criei as tabelas via dump

**Comment by thiagogomesverissimo** [comment]
https://www.developpez.net/forums/d1978207/php/bibliotheques-frameworks/symfony/upgrade-symfony-4-0-4-3-migration/

**Comment by alecostaweb** [comment]
@thiagogomesverissimo, você testou isso? Também não funciona:
There are no commands defined in the "make:migration" namespace.  
                                                                    
  Did you mean one of these?                                        
      doctrine:migrations                                           
      make                                                          
      make:serializer 

Acredito que o comando correto seria:
php bin/console doctrine:migrations:diff

Que também não funciona

**Comment by thiagogomesverissimo** [comment]
Testei, o link diz para mudar caminho da lib de migrations. 
Fiz isso no https://github.com/uspdev/empresta/pull/32 
Pode revisar e fazer o merge?

**Comment by alecostaweb** [comment]
Entendi, devo ter alterado apenas em um arquivo e não percebi o erro. Vi que você alterou em todas as migrations.
