### ISSUE TITLE
Setar quantidade de registros padrão nas listas

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/empresta_symfony#39]
@thiagogomesverissimo há necessidade do knplabs/knp-paginator-bundle, uma vez que utilizamos o DataTables?
Se for necessário, pensei em setar uma variável no .env.dist com um número razoável de registros padrão, ex.:
MAX_RECORDS = 0 para listar todos
MAX_RECORDS = 500 para listar somente os últimos 500 registros
Daí passamos o valor desta variável no knplabs/knp-paginator-bundle

**Comment by thiagogomesverissimo** [comment]
Não é necessário, pode removê-lo se a mesma funcionalidade estiver implementada com dataTables.

**Comment by alecostaweb** [comment]
O dataTables é no cliente, o knp-paginator-bundle faz no servidor/cliente
